### ISSUE TITLE
PostgreSQL 11.x

### ISSUE THREAD

**Issue by grigorov** [lesovsky/pgcenter#58]
I try use pgcenter with PostgreSQL 11.x, and get this error:

```
pgcenter top -U user -h 10.156.0.7 -d backend_prod
Password for user user : ERROR: pq: password authentication failed for user "user"
```
if i will try psql :

```psql -h 10.156.0.7 -d backend_prod -U user 
Password for user user: 
psql (9.6.11, server 11.1 (Ubuntu 11.1-3.pgdg18.04+1))
WARNING: psql major version 9.6, server major version 11.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

backend_prod=# \q
```
password is correct.

**Comment by lesovsky** [comment]
fixed in dev branch 8f1f0a88f68f114af443edc9bf36703d88695589

**Comment by degritsenko** [comment]
i made pgcenter from dev branch and still have the issue
postgress 11

**Comment by lesovsky** [comment]
@degritsenko 
Provide pls more details about your case... parameters, error messages, successful tries with psql, etc...

**Comment by lesovsky** [comment]
can't reproduce the bug with password auth.
![image](https://user-images.githubusercontent.com/953312/55076992-8d84b580-50b8-11e9-9bbe-52c18adf4879.png)

In both cases, after password prompt, pgcenter and psql runs normally, after exit you can see no errors.

**Comment by degritsenko** [comment]
```
-bash-4.2$ pgcenter top -U erldev
ERROR: pq: password authentication failed for user "erldev"
-bash-4.2$ pgcenter --version
pgcenter 0.6.
```
pg_hba.conf 
```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
host    all             all             0.0.0.0/0            md5
```
```
-bash-4.2$ psql -U erldev
psql (11.1)
Type "help" for help.
```

**Comment by lesovsky** [comment]
Do you use `.pgpass` or libpq environment variables such as PQHOST, PGUSER and similar?
What is operation system?

**Comment by degritsenko** [comment]
> Do you use .pgpass or libpq environment variables such as PGHOST, PGUSER and similar?
no

> What is operation system?

rhel 7

**Comment by lesovsky** [comment]
Reproduced in rhel docker container. Try to build e71ec38 and reproduce.

**Comment by degritsenko** [comment]
Thanks a lot, now it's works.

**Comment by MichaelDBA** [comment]
Works for me in PG11 using pgcenter 1.6.2 (downloaded .deb file)  on Ubuntu 16.04 LTS:
pgcenter top -U postgres -h localhost -d mydb

**Comment by lesovsky** [comment]
fixed in release 0.6.2
